name: Update README

on:
  schedule:
    - cron: "00 17 * * 3"
    # Every Wednesday at 17:00 UTC 👻

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install node dependencies
        run: yarn
      - name: Run script that gets latest blog posts
        run: yarn feed
      - name: Git setup
        run: git config --global user.email cliffordmapesa8@gmail.com && git config --global user.name Clifford Mapesa
      - name: Git commit README.md file
        run: git commit -am "BOT Update readme" && git push
